# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*
    - nuget.config
    exclude:
    - README.md

pool:
  vmimage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'
  CakeTarget: 'BuildAndPublish'

steps:
- task: UseDotNet@2
  displayName: ".NET Core 3.1.x"
  inputs:
    version: '3.1.x'
    packageType: sdk

- script: |
    dotnet tool restore
    dotnet tool run dotnet-cake --version
    dotnet tool run dotnet-cake --bootstrap
    dotnet tool run dotnet-cake build.cake --target=$(CakeTarget) --configuration=$(BuildConfiguration)
  displayName: Cake ${{ variables.CakeTarget }} ${{ variables.BuildConfiguration }}
  env:
    NUGET_API_KEY: $(NuGetApiKey)
    MYGET_API_KEY: $(MyGetApiKey)
    SOPI_TESTS_EVENTSTORE__TCPPORT: 1193
    SOPI_TESTS_EVENTSTORE__HTTPPORT: 2193
    SOPI_TESTS_EVENTSTORE__EXTSECURETCPPORT: 1195
    SOPI_TESTS_MONGODB__PORT: 27097
    SOPI_TESTS_AZURECOSMOSDB__AUTHKEY: $(SopiTestCosmosDbPrimaryKey)
    SOPI_TESTS_AZURECOSMOSDB__ENDPOINTURL: $(SopiTestCosmosDbEndpint)
    SOPI_TESTS_AZUREADCLIENT__CLIENTID: $(SopiTestAzureAdClientId)
    SOPI_TESTS_AZUREADCLIENT__CLIENTSECRET: $(SopiTestAzureAdClientSecret)
    SOPI_TESTS_AUTH0CLIENT__CLIENTID: $(SopiTestAuth0ClientId)
    SOPI_TESTS_AUTH0CLIENT__CLIENTSECRET: $(SopiTestAuth0ClientSecret)
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

- task: PublishTestResults@2
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'

- task: CopyFiles@2
  inputs:
    sourceFolder: 'artifacts'
    contents: '**/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop'
    targetPath: $(Build.ArtifactStagingDirectory)
