version: '3.5'

services:

  eventstore:
    image: softwarepioniere/eventstore
    ports:
        - "2193:2193"
        - "1193:1193"
        - "1195:1195"

  mongodb:
    image: mongo:3
    command: --smallfiles
    ports:
      - "27097:27017"
